FROM --platform=${BUILDPLATFORM} docker.io/node:18.19.1-bullseye

COPY . /app
WORKDIR /app

EXPOSE 3000
RUN rm -fr /app/front/node_modules
RUN cd /app/front && npm install && npm install --save react-toastify && yarn add react-toastify
WORKDIR /app/front
ENTRYPOINT ["bash", "-c", "npm run build && npm run start"]
# ENTRYPOINT ["bash", "-c", "npm run dev"]
